const MOJA_BAZA_MATERIALOW = [
    { name: "Bioclean - atomizer do klmiatyzacji 1 litr", uwagi: "", kat: "Chemia HVAC" },
    { name: "Bluza dielektryczna", uwagi: "", kat: "BHP" },
    { name: "Bluza robocza", uwagi: "", kat: "BHP" },
    { name: "Bluza robocza ocieplana", uwagi: "", kat: "BHP" },
    { name: "Buty robocze", uwagi: "", kat: "BHP" },
    { name: "Destructeur D'oeurs Spray 500 ml", uwagi: "Boldair", kat: "Chemia HVAC" },
    { name: "Frionett - atomizer do klimatyzacji 750ml", uwagi: "Activ RTU", kat: "Chemia HVAC" },
    { name: "Frionett Spray - pianka do klimatyzacji 500ml", uwagi: "Activ Foam", kat: "Chemia HVAC" },
    { name: "Kalesony", uwagi: "", kat: "BHP" },
    { name: "Kamizelka ochronna - odblaskowa", uwagi: "", kat: "BHP" },
    { name: "Kask ochronny", uwagi: "", kat: "BHP" },
    { name: "Klucz nastawny", uwagi: "8", kat: "Narzędzia ręczne" },
    { name: "Kombinerki", uwagi: "", kat: "Narzędzia ręczne" },
    { name: "Koszula flanelowa", uwagi: "", kat: "BHP" },
    { name: "Koszulka dielektryczna", uwagi: "", kat: "BHP" },
    { name: "Koszulka T-shirt", uwagi: "", kat: "BHP" },
    { name: "Leak Detector Spray - tester szczelności", uwagi: "Orapi  952", kat: "Chemia HVAC" },
    { name: "Nożyczki", uwagi: "", kat: "Narzędzia ręczne" },
    { name: "Nóż monterski", uwagi: "", kat: "Narzędzia ręczne" },
    { name: "Obcinaczki boczne", uwagi: "", kat: "Narzędzia ręczne" },
    { name: "Okulary ochronne", uwagi: "", kat: "BHP" },
    { name: "Pianka do czyszczenia 500 ml", uwagi: "Orapi 5002", kat: "Chemia HVAC" },
    { name: "Płaszcz przeciwdeszczowy", uwagi: "", kat: "BHP" },
    { name: "Preparat do klimatyzacji 600 ml", uwagi: "Impact Silver", kat: "Chemia HVAC" },
    { name: "Preparat do klimatyzacji 600 ml", uwagi: "Clash Green", kat: "Chemia HVAC" },
    { name: "Rękawce ochronne", uwagi: "", kat: "BHP" },
    { name: "Słuchawki ochronne", uwagi: "", kat: "BHP" },
    { name: "Spodnie dielektryczne", uwagi: "", kat: "BHP" },
    { name: "Spodnie robocze", uwagi: "", kat: "BHP" },
    { name: "Suchy gaz - sprężone powietrze", uwagi: "Orapi 950", kat: "Chemia HVAC" },
    { name: "Szalokominiarka", uwagi: "", kat: "BHP" },
    { name: "Szczypce płaskie", uwagi: "", kat: "Narzędzia ręczne" },
    { name: "Szelki bezpieczeństwa", uwagi: "", kat: "BHP" },
    { name: "Środek do czyszczenia rąk 210 ml", uwagi: "Orapi 5805", kat: "Chemia HVAC" },
    { name: "Torba monterska Milwaukee", uwagi: "", kat: "Narzędzia ręczne" },
    { name: "Torba podróżna na ubrania robocze", uwagi: "Logo KBR", kat: "BHP" },
    { name: "Urządzenie samohamowne", uwagi: "", kat: "BHP" },
    { name: "Wkrętak dielektryczny (płaski + krzyżowy)", uwagi: "", kat: "Narzędzia ręczne" },
    { name: "Wkrętak Milwaukee z grzechotką (14 bitów)", uwagi: "", kat: "Narzędzia ręczne" },
    { name: "Wkrętak Milwaukee z grzechotką (8 bitów)", uwagi: "", kat: "Narzędzia ręczne" }
];